import{a as b,S as L,i as l}from"./assets/vendor-B0XWlCgv.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const v="55861557-2268365b5b48955757ff78c80",w="https://pixabay.com/api/";async function d(s,o){const{data:r}=await b(w,{params:{key:v,q:s,page:o,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}});return r}const S=new L(".photo-container a",{captionsData:"alt",captionDelay:250}),q=document.querySelector(".gallery"),f=document.querySelector(".loader"),p=document.querySelector(".load-more-btn");function m(){S.refresh()}function h(s){return s.map(({webformatURL:o,largeImageURL:r,tags:n,likes:e,views:t,comments:i,downloads:g})=>`<li class="photo-container">
          <a class="photo-link" href="${r}"><img src="${o}" alt="${n}" class="photo-icon"/></a>
            <ul class="info-list">
            <li class="item-info">
                <p class="label">Likes</p>
                <p class="value">${e}</p></li>
            <li class="item-info">
                <p class="label">Views</p>
                <p class="value">${t}</p></li>
            <li class="item-info">
                <p class="label">Comments</p>
                <p class="value">${i}</p></li>
            <li class="item-info">
                <p class="label">Downloads</p>
                <p class="value">${g}</p></li>
            </ul></li>`).join("")}function E(){q.innerHTML=""}function M(){f.classList.add("is-visible")}function P(){f.classList.remove("is-visible")}function $(){p.classList.replace("is-hidden","is-visible")}function H(){p.classList.replace("is-visible","is-hidden")}const B=document.querySelector(".form"),u=document.querySelector("input"),O=document.querySelector(".load-more-btn"),y=document.querySelector(".gallery");let a=1,c="";B.addEventListener("submit",x);O.addEventListener("click",T);function x(s){s.preventDefault();const o=u.value.trim();if(!o){l.warning({message:"Please, enter a search query"});return}c=o,u.value="",M(),E(),d(c,a).then(r=>{if(r.hits.length===0){l.warning({message:"Sorry, there are no images matching your search query. Please try again!"});return}y.innerHTML=h(r.hits),m();const n=Math.ceil(r.totalHits/15);console.log(a,n),a<n&&$()}).catch(r=>{l.error({message:"Something went wrong. Please try again later."})}).finally(()=>{P()})}async function T(){a++;try{const s=await d(c,a);y.insertAdjacentHTML("beforeend",h(s.hits));const o=document.querySelector(".photo-container");m();const r=o.getBoundingClientRect().height;window.scrollBy({top:2*r,behavior:"smooth"});const n=Math.ceil(s.totalHits/15);a>=n&&(l.error({message:"We're sorry, but you've reached the end of search results."}),H())}catch(s){console.log(s),l.error({message:"Something went wrong. Please try again later."})}}
//# sourceMappingURL=index.js.map
