import{a as q,S as P,i}from"./assets/vendor-B0XWlCgv.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const E="55861557-2268365b5b48955757ff78c80",M="https://pixabay.com/api/";async function f(s,r){const{data:o}=await q(M,{params:{key:E,q:s,page:r,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}});return o}const $=new P(".photo-container a",{captionsData:"alt",captionDelay:250}),p=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-more-btn");function y(){$.refresh()}function g(s){const r=s.map(({webformatURL:o,largeImageURL:a,tags:e,likes:t,views:l,comments:w,downloads:S})=>`<li class="photo-container">
          <a class="photo-link" href="${a}"><img src="${o}" alt="${e}" class="photo-icon"/></a>
            <ul class="info-list">
            <li class="item-info">
                <p class="label">Likes</p>
                <p class="value">${t}</p></li>
            <li class="item-info">
                <p class="label">Views</p>
                <p class="value">${l}</p></li>
            <li class="item-info">
                <p class="label">Comments</p>
                <p class="value">${w}</p></li>
            <li class="item-info">
                <p class="label">Downloads</p>
                <p class="value">${S}</p></li>
            </ul></li>`).join("");p.insertAdjacentHTML("beforeend",r),y()}function B(){p.innerHTML=""}function b(){m.classList.add("is-visible")}function L(){m.classList.remove("is-visible")}function v(){h.classList.replace("is-hidden","is-visible")}function c(){h.classList.replace("is-visible","is-hidden")}const H=document.querySelector(".form"),d=document.querySelector("input"),O=document.querySelector(".load-more-btn");let n=1,u="";H.addEventListener("submit",x);O.addEventListener("click",A);async function x(s){s.preventDefault();const r=d.value.trim();if(!r){i.warning({message:"Please, enter a search query"});return}u=r,n=1,d.value="",b(),B(),f(u,n).then(o=>{if(o.hits.length===0){i.warning({message:"Sorry, there are no images matching your search query. Please try again!"});return}g(o.hits);const a=Math.ceil(o.totalHits/15);n<a?v():(i.error({message:"We're sorry, but you've reached the end of search results."}),c())}).catch(o=>{i.error({message:"Something went wrong. Please try again later."})}).finally(()=>{L()})}async function A(){b(),c(),n++;try{const s=await f(u,n);g(s.hits);const r=document.querySelector(".photo-container");y();const o=r.getBoundingClientRect().height;window.scrollBy({top:2*o,behavior:"smooth"});const a=Math.ceil(s.totalHits/15);n>=a&&(i.error({message:"We're sorry, but you've reached the end of search results."}),c())}catch{i.error({message:"Something went wrong. Please try again later."})}finally{L(),v()}}
//# sourceMappingURL=index.js.map
