import{a as P,S as E,i as n}from"./assets/vendor-B0XWlCgv.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const l of t.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const M="55861557-2268365b5b48955757ff78c80",$="https://pixabay.com/api/";async function p(s,r){const{data:o}=await P($,{params:{key:M,q:s,page:r,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}});return o}const B=new E(".photo-container a",{captionsData:"alt",captionDelay:250}),m=document.querySelector(".gallery"),h=document.querySelector(".loader"),y=document.querySelector(".load-more-btn");function g(){B.refresh()}function b(s){const r=s.map(({webformatURL:o,largeImageURL:i,tags:e,likes:t,views:l,comments:S,downloads:q})=>`<li class="photo-container">
          <a class="photo-link" href="${i}"><img src="${o}" alt="${e}" class="photo-icon"/></a>
            <ul class="info-list">
            <li class="item-info">
                <p class="label">Likes</p>
                <p class="value">${t}</p></li>
            <li class="item-info">
                <p class="label">Views</p>
                <p class="value">${l}</p></li>
            <li class="item-info">
                <p class="label">Comments</p>
                <p class="value">${S}</p></li>
            <li class="item-info">
                <p class="label">Downloads</p>
                <p class="value">${q}</p></li>
            </ul></li>`).join("");m.insertAdjacentHTML("beforeend",r),g()}function H(){m.innerHTML=""}function L(){h.classList.add("is-visible")}function v(){h.classList.remove("is-visible")}function w(){y.classList.replace("is-hidden","is-visible")}function c(){y.classList.replace("is-visible","is-hidden")}const O=document.querySelector(".form"),f=document.querySelector("input"),x=document.querySelector(".load-more-btn");let a=1,u="",d=0;O.addEventListener("submit",A);x.addEventListener("click",D);async function A(s){s.preventDefault();const r=f.value.trim();if(!r){n.warning({message:"Please, enter a search query"});return}u=r,a=1,f.value="",L(),H(),c();try{const o=await p(u,a);if(o.hits.length===0){n.warning({message:"Sorry, there are no images matching your search query. Please try again!"});return}b(o.hits),d=Math.ceil(o.totalHits/15),a<d?w():(n.error({message:"We're sorry, but you've reached the end of search results."}),c())}catch{n.error({message:"Something went wrong. Please try again later."})}finally{v()}}async function D(){L(),c(),a++;try{const s=await p(u,a);b(s.hits);const r=document.querySelector(".photo-container");g();const o=r.getBoundingClientRect().height;window.scrollBy({top:2*o,behavior:"smooth"});const i=Math.ceil(s.totalHits/15);a>=i&&(n.error({message:"We're sorry, but you've reached the end of search results."}),c())}catch{n.error({message:"Something went wrong. Please try again later."})}finally{v(),a<d&&w()}}
//# sourceMappingURL=index.js.map
